### ISSUE TITLE
Using the plugin on desktop editor

### ISSUE THREAD

**Issue by filippogambarota** [ONLYOFFICE/onlyoffice.github.io#114]

**Comment by Aybee5** [comment]
I saw that this issue has been closed. Has a workaround been developed for this issue?

I installed the plugin on my Desktop editor, and it says the desktop editor does not work.

I am using the Community version 9.0.4.50 (deb) version of ONLYOFFICE.

<img width="441" height="715" alt="Image" src="https://github.com/user-attachments/assets/d411cff0-5a85-4994-8769-fab01effd432" />
