### ISSUE TITLE
Support of Deepl free plan

### ISSUE THREAD

**Issue by Silverhawk85** [ONLYOFFICE/onlyoffice.github.io#126]
Hi,

I have a problem with inserting the API Key.
I always get the message that the key is not correct.
I have generated and inserted a new key a few times now. Always the same problem.

**Comment by christianhalter** [comment]
I have the same problem than @Copy2Translator , message "Connection failed!"
ONLYOFFICE Community version 9.0.4.50 (x64 exe), Windows 10
