### ISSUE TITLE
Error regarding LanguageTool API - Plugin would not operate against local instance

### ISSUE THREAD

**Issue by ITISAG-OCA** [ONLYOFFICE/onlyoffice.github.io#133]
Dear all: 
Many thanks for providing this plugin. We wanted to try out, and installation appeared to work smooth, but it would not operate against a local instance of the server: Error is this:

**Error: Missing arguments for LanguageTool API. Please see https://languagetool.org/http-api/swagger-ui/#/default**

Local LT server works fine with browser plugins etc. 

Version of OnlyOffice: ONLYOFFICE Desktop Editors Version 6.4.2.6, plugin download from yesterday, plugin-languagetool-master.plugin renamed to (copy).zip for upload on git is attached.
[plugin-languagetool-master (copy).zip](https://github.com/ONLYOFFICE/plugin-languagetool/files/7674849/plugin-languagetool-master.copy.zip)
Many thanks for looking into this.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
