### ISSUE TITLE
Add tags to this repository

### ISSUE THREAD

**Issue by Willena** [ONLYOFFICE/onlyoffice.github.io#150]
Hi ! 

Would it be possible to add tags on this repository with a version specific to this repository or one that correspond with the version shipped with the document server ?

Context: I wrote one plugin, and I'm worried of files in sdkjs-plugins/v1 that could be updated and break the plugin.
With tags on the repository, I would be able to import a given version. One other solution would be for me to use the commit ID as version.

**Comment by ShockwaveNN** [comment]
Hi, just have a talk with our developers and they are planning not to break any compatibility with v1 API in any updates

If something change - it will be changed in v2 of sdkjs-plungs subfolder
