### ISSUE TITLE
Cant add wordcounter plugin to windows desktop editor

### ISSUE THREAD

**Issue by devtahmid** [ONLYOFFICE/onlyoffice.github.io#156]
I have downloaded the code from https://github.com/ONLYOFFICE/plugin-wordscounter , extracted it, made a new zip that contains resources, index.html, config.json, and code.js and changed the zip extension to .plugin. When I add the plugin to onlyoffice, nothing happens, it doesn't show up on the installed plugins space. However when I just have a folder that contains resources, index.html, and config.json and paste it in the DesktopEditors\editors\sdkjs-plugins folder, the plugin shows up. 
There is still a problem, the icon does not show[1] and when I click on the plugin, it shows a screen that says I dont have internet connection[2], even though I do. 

1. 
![image](https://user-images.githubusercontent.com/27241074/197135038-3c434eef-782a-4a5b-b873-df64e9b3960b.png)

2. 
![image](https://user-images.githubusercontent.com/27241074/197134902-68e58666-581e-4666-a23f-81223efdc7fc.png)

**Comment by ShockwaveNN** [comment]
Could you attach plugin file, I sill think in may be not properly packed

**Comment by devtahmid** [comment]
I tried uploading here but it doesnt accept the .plugin extension so i uploaded it to tmp.ninja . https://a.tmp.ninja/qjfFyfJw.plugin

**Comment by ShockwaveNN** [comment]
![image](https://user-images.githubusercontent.com/668524/197186720-7c8e34da-5ddb-4829-ac1a-54fc44a125bc.png)

You got subfolder in this archive

This is not correct

See [FAQ](https://api.onlyoffice.com/plugin/faq) entry "I packed the plugin folder to the archive, changed its extension to .plugin and added it to the editors. But it doesn’t work. What should I do?"

**Comment by devtahmid** [comment]
Thank you very much. I followed the steps but now the values are not showing up. 
![image](https://user-images.githubusercontent.com/27241074/197215987-73c3b2d0-d73b-4f97-9dc7-e231be05c2b4.png)
Really appreciate your help

**Comment by ShockwaveNN** [comment]
Which version of DesktopEditors are you using?

**Comment by devtahmid** [comment]
ONLYOFFICE Desktop Editors version 7.1.1.57

**Comment by ShockwaveNN** [comment]
I think it may be incompatible with latest plugin (or you don't using latest plugin) and you should update both DesktopEditors and plugin

**Comment by devtahmid** [comment]
Hi, I updated my editor but it did not work. So I downloaded the plugin again from this repository and it worked. Previously I downloaded the plugin from the archived repository as the Install button on the [onlyoffice page](https://www.onlyoffice.com/en/app-directory/word-counter) directed me to the archived repo. So I suggest changing the path of the install button to this repo. Really appreciate your help, thank you

**Comment by ShockwaveNN** [comment]
I think you've doing something wrong

I've installed plugin from [release](https://github.com/ONLYOFFICE/plugin-wordscounter/releases/tag/v1.0.0) page to current stable version of DesktopEditors and it's working

![image](https://user-images.githubusercontent.com/668524/197533478-226f5eab-4ea1-4983-a7bc-fa59fa02106b.png)

**Comment by devtahmid** [comment]
Perhaps I downloaded it wrong then. I downloaded the repo instead of downloading from the release page. Thank you for your efforts

**Comment by ShockwaveNN** [comment]
You're welcome. I'm closing this issue
