### ISSUE TITLE
Cannot install plugins through the plugin manager

### ISSUE THREAD

**Issue by KafCoppelia** [ONLYOFFICE/onlyoffice.github.io#174]
It is wired that even if I followed the [plugin installation guide](https://api.onlyoffice.com/plugin/installation/desktop) on Archlinux, onlyoffice cannot recognize the `.plugin` file after packing all the plugin files within the plugin folder into a `zip` archive (I use Ark) and changing its extension to `.plugin`.

Even if I added the `.plugin` file in onlyoffice forcely, it didn't work. I can only use `Adding plugin through the plugin folder` method instead. For example, onlyoffice cannot detect the `drawio.plugin` even if the `files of type` is `*.plugin`.

![image](https://user-images.githubusercontent.com/69038090/215259782-59917624-75c9-4f9b-bf1c-308caa4ec221.png)

**Comment by GeoffClements** [comment]
I found the video instructions to be quite confusing. In the end I discovered that you have to create a zip file _inside_ the plugin directory and include all the files and folders within that directory, and then rename the file extension to .plugin.

From your picture it looks like you've zipped up the entire plugin directory from outside the directory. I did this at first and it didn't work, as you've found.

**Comment by KafCoppelia** [comment]
Thank you, @GeoffClements. It works although I need to add `*.plugin` forcely due to:

> onlyoffice cannot detect the drawio.plugin even if the files of type is `*.plugin`.

I didn't watch the video instructions at first. The video is clear but the guide is confusing. Maybe the right way of creating `.zip` file isn't emphasized in the video.

Hope the staff will improve the guide.
