### ISSUE TITLE
OCR: list of langs not ordered, bad quality

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/onlyoffice.github.io#178]
Hi! I would like to submit two bugs in relation to the OCR plugin.
Firstly, the list of languages is not in alphabetical order. 
Secondly, sadly, the quality of OCR is very low. See below.

![image](https://user-images.githubusercontent.com/5199030/218747392-30d6e5fa-f6b7-403d-84fb-b8d6ae325a01.png)

**Comment by AlexeyMatveev686** [comment]
Hello, thanks, for your issue. We've fixed it. Now the list of languages is not in alphabetical order.
Unfortunally we can't reduce time of recognizing. With this problem you could create an issue into the original library [repo](https://github.com/naptha/tesseract.js).
