### ISSUE TITLE
Zotero references separated by commas in bibliography

### ISSUE THREAD

**Issue by parrenin** [ONLYOFFICE/onlyoffice.github.io#194]
I tested the new Zotero plugin, which works great thanks!
One issue I noticed is that references are separated by commas in the bibliography.
I tried with different styles (Copernicus, Nature, etc.) but it is all the same problem.

<img width="1508" alt="Capture d’écran 2023-04-15 à 12 17 45" src="https://user-images.githubusercontent.com/4678272/232207992-2f92823a-3d2e-4ab5-ab15-f0d0fadce474.png">

**Comment by VladimirProkofiev52** [comment]
Hello! @parrenin, I confirm, this is bug.
I created the bug, issue 62200 in our private issue tracker.
Thank you for report.

**Comment by parrenin** [comment]
I think this is fixed now and this bug report could be closed.

**Comment by VladimirProkofiev52** [comment]
Hello! @parrenin 
You are right, our specialists fixed this problem. 
We close this issue.
