### ISSUE TITLE
Zotero In-text Citation issue

### ISSUE THREAD

**Issue by risayap** [ONLYOFFICE/onlyoffice.github.io#199]
Hello there,

I am appreciating the Zotero plugin, however I am finding it quite buggy.

I initially installed OnlyOffice through the software manager, followed the installation guide but couldn’t get the latest Zotero plugin to work properly. Specifically, it gets stuck at loading whenever I try to insert an in-text citation. I uninstalled the flatpak and tried to use the AppImage file. Initially, I managed to get it to work, however it fell back to the same issue.

[Screenshot of issue](https://forum.onlyoffice.com/uploads/default/original/2X/7/7a12b9a8ede2428653365acc3b6dd8d7afded315.png)

Is there any recommendations on how to go about this issue?

Thank you very much.

OS: LinuxMint 21.1 Vera (Cinammon Edition)
Browser version: Firefox

**Comment by VladimirProkofiev52** [comment]
Hi! @risayap,
Tell me please, you are using Desktop version editor or WEB version?

Tell me the version of the editor that reproduces the problem, for example: "Version: 7.3.3.50"

**Comment by risayap** [comment]
![image](https://github.com/ONLYOFFICE/onlyoffice.github.io/assets/132810970/550cfa2d-e969-4caa-a7e6-1427f0e54f39)

Hello again,

I have attached the screenshot of the version. It's desktop editor (flatpak that I used for the debug) and it's v7.3.3.50

Thanks again!

**Comment by DenisDeeSign** [comment]
@risayap, Seems you opened the same request at our forum and a post contains more information so I close that issue.
