### ISSUE TITLE
Document QA for chatgpt plugin

### ISSUE THREAD

**Issue by Microwave-WYB** [ONLYOFFICE/onlyoffice.github.io#212]
Current version only have very limited functions. It takes in a text prompt and write the results to the document. But we can build a QA chat mode using langchain's document qa chain to allow question answering on the opened document.

**Comment by VladimirProkofiev52** [comment]
Hello! @Microwave-WYB,
We recently released version 7.4 of the editors.
The new version contains an updated plug-in Chat GPT in Plugin Manager.
The new version has a chat mode and much more.
