### ISSUE TITLE
ChatGPT Plugin for OnlyOffice 7.5.0

### ISSUE THREAD

**Issue by rdenarie** [ONLYOFFICE/onlyoffice.github.io#299]
Hello
The current version of ChatGPT plugin (1.1.2) seems not working on onlyOffirce 7.5.0 :
Nothing happens when clicking on chat gpt plugin button.

Do you plan an update for being compatible with OO 7.5 ?

Thanks a lot

**Comment by rdenarie** [comment]
Oh !

I didnt notice that point.
Thanks a lot for your answer.

**Comment by VladimirProkofiev52** [comment]
We are closing this issue as irrelevant.
