### ISSUE TITLE
ChatGPT for desktop does NOT work

### ISSUE THREAD

**Issue by pigeonskiller** [ONLYOFFICE/onlyoffice.github.io#315]
It does not work. Tested both the latest desktop version and the previous one on Linux and Windows with different API keys. Both give the same error even though they have not exceeded any quota:
"Error:
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors."
The same error is reported by many other users.
It probably only works with a paid API, but OnlyOffice should declare it...

**Comment by VladimirProkofiev52** [comment]
Hello! @pigeonskiller Earlier, we responded to this issue [here](https://github.com/ONLYOFFICE/onlyoffice.github.io/discussions/248#discussioncomment-8371719). Please refrain from creating duplicate inquiries in the future. 
Thank you for your report.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
