### ISSUE TITLE
Summarize cell values based on cell color 

### ISSUE THREAD

**Issue by TatyanaSmolentseva** [ONLYOFFICE/onlyoffice.github.io#339]
There is a macro for Google that allows to add a custom function:

`function sumColoredCells(sumRange,colorRef) {
  var activeRg = SpreadsheetApp.getActiveRange();
  var activeSht = SpreadsheetApp.getActiveSheet();
  var activeformula = activeRg.getFormula();
  var countRangeAddress = activeformula.match(/\((.*)\,/).pop().trim();
  var backGrounds = activeSht.getRange(countRangeAddress).getBackgrounds();
  var sumValues = activeSht.getRange(countRangeAddress).getValues();  
  var colorRefAddress = activeformula.match(/\,(.*)\)/).pop().trim();
  var BackGround = activeSht.getRange(colorRefAddress).getBackground();
  var totalValue = 0;
  for (var i = 0; i < backGrounds.length; i++)
    for (var k = 0; k < backGrounds[i].length; k++)
      if ( backGrounds[i][k] == BackGround )
        if ((typeof sumValues[i][k]) == 'number')
          totalValue = totalValue + (sumValues[i][k]);
  return totalValue;
};`
Please help me adapt it to onlyoffice. All my attempts are non-working. If custom function don't work, then what other way can you solve this problem?

**Comment by askonev** [comment]
@TatyanaSmolentseva At the moment, we are testing functionality related to the installation of custom functions in the table editor. In the current release and in the documentation you will find information about adapting your scripts to ONLYOFFICE macros

**Comment by TatyanaSmolentseva** [comment]
Thank you! Can you please tell me if the current issue has some kind of release date or when ready?

**Comment by askonev** [comment]
@TatyanaSmolentseva yea, after release I will notify you

**Comment by TatyanaSmolentseva** [comment]
> @TatyanaSmolentseva да, после выпуска я уведомлю вас

Thanks!)

**Comment by askonev** [comment]
@TatyanaSmolentseva  In version 8.1, the functionality for custom functions is implemented https://api.onlyoffice.com/officeapi/changelog

```log
Custom function methods

Added the [Api/AddCustomFunction](https://api.onlyoffice.com/officeapi/spreadsheetapi/api/addcustomfunction) method to Spreadsheet API.
Added the [Api/ClearCustomFunctions](https://api.onlyoffice.com/officeapi/spreadsheetapi/api/clearcustomfunctions) method to Spreadsheet API.
Added the [Api/RemoveCustomFunction](https://api.onlyoffice.com/officeapi/spreadsheetapi/api/removecustomfunction) method to Spreadsheet API.

**Comment by Rita-Bubnova** [comment]
DocumentServer v8.1.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by TatyanaSmolentseva** [comment]
@Rita-Bubnova Hello! Thanks! Please help me adapt the macro above so that it works in ONLYOFFICE. I can't do it ((

**Comment by alexanderonlyoffice** [comment]
@TatyanaSmolentseva, hello, please find the documentation https://api.onlyoffice.com/plugin/convertingvbamacros describing the conversion of VBA macros into ONLYOFFICE macros. There are also a lot of macros samples that might be helpful to show how macros are written. 

If you would like us to assist in macros creation, please feel free to contact our sales department at sales@onlyoffice.com to discuss allocating the resources for this task.
