### ISSUE TITLE
Zotero plugin Does not update the numbering order of quotations

### ISSUE THREAD

**Issue by anthonychaussin** [ONLYOFFICE/onlyoffice.github.io#340]
When a new citation is inserted between two others already present, the numbering order is not updated.
This is very annoying because it means that you can't update a document with a new citation without starting all over again.
Normally, citations should always appear in the order in which they appear in the document.

Could you please include this little fix in your next update?

<img width="391" alt="image" src="https://github.com/ONLYOFFICE/onlyoffice.github.io/assets/43750490/0730718a-d6e1-4750-a034-b39932ec1c7e">

**Comment by VladimirProkofiev52** [comment]
Hello! @anthonychaussin Your issue is a duplicate, all discussions will be directed to another one. If you have any additional questions, please write them in this https://github.com/ONLYOFFICE/onlyoffice.github.io/issues/336.
