### ISSUE TITLE
How to communicate with plugins outside the editor, such as executing a method of the plugin

### ISSUE THREAD

**Issue by qzzhujixue** [ONLYOFFICE/onlyoffice.github.io#357]
How to communicate with plugins outside the editor, such as executing a method of the plugin

**Comment by askonev** [comment]
@qzzhujixue Greetings. When you purchase a license with "advanced_api": true, you can use the functionality of the editor integrated into html

It is not possible to use the plugin api using the rest api

https://api.onlyoffice.com/editors/connector

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
